package cgroups

type metric struct {
	ns          string
	description string
	unit        string
}

var allMetrics = []metric{
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_merged_recursive/*/major", description: "Number of bios/requests merged into requests belonging to all the descendant cgroups (major)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_merged_recursive/*/minor", description: "Number of bios/requests merged into requests belonging to all the descendant cgroups (minor)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_merged_recursive/*/op", description: "Number of bios/requests merged into requests belonging to all the descendant cgroups (operation)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_merged_recursive/*/value", description: "Number of bios/requests merged into requests belonging to all the descendant cgroups (value)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_queue_recursive/*/major", description: "Number of requests queued up at any given instant from all the descendant cgroups (major)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_queue_recursive/*/minor", description: "Number of requests queued up at any given instant from all the descendant cgroups (minor)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_queue_recursive/*/op", description: "Number of requests queued up at any given instant from all the descendant cgroups (operation)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_queue_recursive/*/value", description: "Number of requests queued up at any given instant from all the descendant cgroups (value)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_service_bytes_recursive/*/major", description: "Number of bytes transferred to/from the disk from all the descendant cgroups (major)", unit: "B"},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_service_bytes_recursive/*/minor", description: "Number of bytes transferred to/from the disk from all the descendant cgroups (minor)", unit: "B"},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_service_bytes_recursive/*/op", description: "Number of bytes transferred to/from the disk from all the descendant cgroups (operation)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_service_bytes_recursive/*/value", description: "Number of bytes transferred to/from the disk from all the descendant cgroups (value)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_service_time_recursive/*/major", description: "Amount of time between request dispatch and request completion from all the descendant cgroups (major)", unit: "ns"},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_service_time_recursive/*/minor", description: "Amount of time between request dispatch and request completion from all the descendant cgroups (minor)", unit: "ns"},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_service_time_recursive/*/op", description: "Amount of time between request dispatch and request completion from all the descendant cgroups (operation)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_service_time_recursive/*/value", description: "Amount of time between request dispatch and request completion from all the descendant cgroups (value)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_serviced_recursive/*/major", description: "Total number of block I/O requests serviced in that container (major)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_serviced_recursive/*/minor", description: "Total number of block I/O requests serviced in that container (minor)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_serviced_recursive/*/op", description: "Total number of block I/O requests serviced in that container (operation)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_serviced_recursive/*/value", description: "Total number of block I/O requests serviced in that container (value)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_time_recursive/*/major", description: "Disk time allocated to all devices from all the descendant cgroups (major)", unit: "ns"},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_time_recursive/*/minor", description: "Disk time allocated to all devices from all the descendant cgroups (minor)", unit: "ns"},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_time_recursive/*/op", description: "Disk time allocated to all devices from all the descendant cgroups (operation)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_time_recursive/*/value", description: "Disk time allocated to all devices from all the descendant cgroups (value)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_wait_time_recursive/*/major", description: "Amount of time the IOs for this cgroup spent waiting in the scheduler queues for service from all the descendant cgroups (major)", unit: "ns"},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_wait_time_recursive/*/minor", description: "Amount of time the IOs for this cgroup spent waiting in the scheduler queues for service from all the descendant cgroups (minor)", unit: "ns"},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_wait_time_recursive/*/op", description: "Amount of time the IOs for this cgroup spent waiting in the scheduler queues for service from all the descendant cgroups (operation)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/io_wait_time_recursive/*/value", description: "Amount of time the IOs for this cgroup spent waiting in the scheduler queues for service from all the descendant cgroups (value)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/sectors_recursive/*/major", description: "Number of sectors transferred to/from disk bys from all the descendant cgroups (major)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/sectors_recursive/*/minor", description: "Number of sectors transferred to/from disk bys from all the descendant cgroups (minor)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/sectors_recursive/*/op", description: "Number of sectors transferred to/from disk bys from all the descendant cgroups (operation)", unit: ""},
	{ns: "/intel/linux/cgroups/blkio_stats/*/sectors_recursive/*/value", description: "Number of sectors transferred to/from disk bys from all the descendant cgroups (value)", unit: ""},
	{ns: "/intel/linux/cgroups/cpu_stats/*/throttling_data/periods", description: "Number of period intervals that have elapsed", unit: ""},
	{ns: "/intel/linux/cgroups/cpu_stats/*/throttling_data/throttled_periods", description: "Number of times tasks in a cgroup have been throttled", unit: ""},
	{ns: "/intel/linux/cgroups/cpu_stats/*/throttling_data/throttled_time", description: "Total time duration for which tasks in a cgroup have been throttled", unit: "ns"},
	{ns: "/intel/linux/cgroups/cpu_stats/*/cpu_usage/percpu_usage/*/value", description: "CPU time consumed on each CPU by all tasks", unit: "ns"},
	{ns: "/intel/linux/cgroups/cpu_stats/*/cpu_usage/total_usage", description: "Total CPU time consumed", unit: "ns"},
	{ns: "/intel/linux/cgroups/cpu_stats/*/cpu_usage/usage_in_kernelmode", description: "CPU time consumed by tasks in system (kernel) mode", unit: "ns"},
	{ns: "/intel/linux/cgroups/cpu_stats/*/cpu_usage/usage_in_usermode", description: "CPU time consumed by tasks in user mode", unit: "ns"},
	{ns: "/intel/linux/cgroups/cpu_stats/*/throttling_data/periods", description: "Number of period intervals that have elapsed", unit: ""},
	{ns: "/intel/linux/cgroups/cpu_stats/*/throttling_data/throttled_periods", description: "Number of times tasks in a cgroup have been throttled", unit: ""},
	{ns: "/intel/linux/cgroups/cpu_stats/*/throttling_data/throttled_time", description: "Total time duration for which tasks in a cgroup have been throttled", unit: "ns"},
	{ns: "/intel/linux/cgroups/cpuacct_stats/*/throttling_data/periods", description: "Number of period intervals that have elapsed", unit: ""},
	{ns: "/intel/linux/cgroups/cpuacct_stats/*/throttling_data/throttled_periods", description: "Number of times tasks in a cgroup have been throttled", unit: ""},
	{ns: "/intel/linux/cgroups/cpuacct_stats/*/throttling_data/throttled_time", description: "Total time duration for which tasks in a cgroup have been throttled", unit: "ns"},
	{ns: "/intel/linux/cgroups/cpuacct_stats/*/cpu_usage/percpu_usage/*/value", description: "CPU time consumed on each CPU by all tasks", unit: "ns"},
	{ns: "/intel/linux/cgroups/cpuacct_stats/*/cpu_usage/total_usage", description: "Total CPU time consumed", unit: "ns"},
	{ns: "/intel/linux/cgroups/cpuacct_stats/*/cpu_usage/usage_in_kernelmode", description: "CPU time consumed by tasks in system (kernel) mode", unit: "ns"},
	{ns: "/intel/linux/cgroups/cpuacct_stats/*/cpu_usage/usage_in_usermode", description: "CPU time consumed by tasks in user mode", unit: "ns"},
	{ns: "/intel/linux/cgroups/cpuacct_stats/*/throttling_data/periods", description: "Number of period intervals that have elapsed", unit: ""},
	{ns: "/intel/linux/cgroups/cpuacct_stats/*/throttling_data/throttled_periods", description: "Number of times tasks in a cgroup have been throttled", unit: ""},
	{ns: "/intel/linux/cgroups/cpuacct_stats/*/throttling_data/throttled_time", description: "Total time duration for which tasks in a cgroup have been throttled", unit: "ns"},
	{ns: "/intel/linux/cgroups/hugetlb_stats/*/*/failcnt", description: "Report the number of allocation failure due to HugeTLB limit", unit: ""},
	{ns: "/intel/linux/cgroups/hugetlb_stats/*/*/max_usage", description: "Report max hugepagesize HugeTLB usage recorded", unit: "B"},
	{ns: "/intel/linux/cgroups/hugetlb_stats/*/*/usage", description: "Report current usage for hugepagesize HugeTLB", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/cache", description: "Page cache including tmpfs", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/kernel_tcp_usage/failcnt", description: "Reports the number of times that the kernel TCP stack memory limit has reached the value set in memory.limit_in_bytes", unit: ""},
	{ns: "/intel/linux/cgroups/memory_stats/*/kernel_tcp_usage/limit", description: "Memory usage limit for kernel TCP stack", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/kernel_tcp_usage/max_usage", description: "Maximum memory usage by kernel TCP stack reported", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/kernel_tcp_usage/usage", description: "Memory usage by kernel TCP stack", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/kernel_usage/failcnt", description: "Reports the number of times that the kernel memory limit has reached the value set in memory.limit_in_bytes", unit: ""},
	{ns: "/intel/linux/cgroups/memory_stats/*/kernel_usage/limit", description: "Memory usage limit for kernel", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/kernel_usage/max_usage", description: "Maximum memory usage by kernel reported", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/kernel_usage/usage", description: "Memory usage by kernel", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/active_anon", description: "Number of bytes of anonymous and swap cache memory on active LRU list", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/active_file", description: "Number of bytes of file-backed memory on active LRU list", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/cache", description: "Number of bytes of page cache memory", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/dirty", description: "Number of bytes that are waiting to get written back to the disk", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/hierarchical_memory_limit", description: "Number of bytes of memory limit with regard to hierarchy under which the memory cgroup is", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/inactive_anon", description: "Amount of buffer or page cache memory that are free and available", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/inactive_file", description: "Number of bytes of file-backed memory on inactive LRU list", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/mapped_file", description: "Number of bytes of mapped file (includes tmpfs/shmem)", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/pgfault", description: "Number of page faults per second", unit: ""},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/pgmajfault", description: "Number of major page faults per second", unit: ""},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/pgpgin", description: "Number of charging events to the memory cgroup", unit: ""},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/pgpgout", description: "Number of uncharging events to the memory cgroup", unit: ""},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/rss", description: "Number of bytes of anonymous and swap cache memory", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/rss_huge", description: "Number of bytes of anonymous transparent hugepages", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/total_active_anon", description: "Total number of bytes of anonymous and swap cache memory on active LRU list in all children's active_anon", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/total_active_file", description: "Total number of bytes of file-backed memory on active LRU list in all children's active_file", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/total_cache", description: "Total number of bytes of page cache memory in all children's cache", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/total_dirty", description: "Total number of bytes that are waiting to get written back to the disk in all children's dirty", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/total_inactive_anon", description: "The total amount of buffer or page cache memory that are free and available in all children's total_inactive", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/total_inactive_file", description: "Total number of bytes of file-backed memory on inactive LRU list in all children's inactive_file", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/total_mapped_file", description: "Total number of bytes of mapped file (includes tmpfs/shmem) in all children's mapped_file", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/total_pgfault", description: "Total number of page faults per second in all children's pgfault", unit: ""},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/total_pgmajfault", description: "Total number of page major faults which happened since the creation of the cgroup in all children's pgmajfault", unit: ""},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/total_pgpgin", description: "Total number of charging events to the memory cgroup in all children's pgpin", unit: ""},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/total_pgpgout", description: "Number of uncharging events to the memory cgroup in all children's pgpout", unit: ""},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/total_rss", description: "Total number of bytes of anonymous and swap cache memory in all children's rss", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/total_rss_huge", description: "Total number of bytes of anonymous transparent hugepages in all children's rss_huge", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/total_unevictable", description: "Total number of bytes of memory that cannot be reclaimed (mlocked etc) in all children's unevictable", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/total_writeback", description: "Total number of bytes of file/anon cache that are queued for syncing to disk in all children's writeback", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/unevictable", description: "Number of bytes of memory that cannot be reclaimed (mlocked etc)", unit: "B"},
	{ns: "/intel/linux/cgroups/memory_stats/*/stats/writeback", description: "Number of bytes of file/anon cache that are queued for syncing to disk", unit: "B"},
	{ns: "/intel/linux/cgroups/*/swap_usage/failcnt", description: "Reports the number of times the swap space limit has reached the value set in memorysw.limit_in_bytes", unit: ""},
	{ns: "/intel/linux/cgroups/*/swap_usage/limit", description: "Reports the limit of swap space usage by porcesses in the cgroup", unit: ""},
	{ns: "/intel/linux/cgroups/*/swap_usage/max_usage", description: "Reports the maximum swap space used by processes in the cgroup", unit: ""},
	{ns: "/intel/linux/cgroups/*/swap_usage/usage", description: "Reports the total swap space usage by processes in the cgroup", unit: ""},
	{ns: "/intel/linux/cgroups/*/usage/failcnt", description: "Reports the number of times that the memory limit has reached the value set in memory.limit_in_bytes", unit: ""},
	{ns: "/intel/linux/cgroups/*/usage/limit", description: "Memory usage limit for processes in the cgroup", unit: "B"},
	{ns: "/intel/linux/cgroups/*/usage/max_usage", description: "Maximum memory usage by processes in the cgroup reported", unit: "B"},
	{ns: "/intel/linux/cgroups/*/usage/usage", description: "Memory usage by processes in the cgroup", unit: "B"},
	{ns: "/intel/linux/cgroups/*/pids_stats/current", description: "Number of processes currently in the cgroup", unit: ""},
	{ns: "/intel/linux/cgroups/*/pids_stats/limit", description: "Limit of processes currently in the cgroup", unit: ""},
}
